name: Start Codespace and Application

on:
  schedule:
    - cron: '50 9 * * 1-5' # Runs at 9:15 AM, Monday-Friday

jobs:
  start-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Start Codespace
        run: |
          echo "Starting the Codespace..."
          CODESPACE_ID=$(gh codespace create --repo ${{ github.repository }} --wait)
          echo "Codespace ID: $CODESPACE_ID"
          echo "Making the port public..."
          gh codespace ports visibility 3000:public --codespace $CODESPACE_ID
          echo "Starting the application..."
          gh codespace exec --codespace $CODESPACE_ID -- npm run start
          URL=$(gh codespace view --json webUrl --codespace $CODESPACE_ID | jq -r '.webUrl')
          echo "Application URL: $URL"
          echo "Timeout set to maximum."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
