name: Stop Application and Codespace

on:
  schedule:
    - cron: '30 13 * * 1-5'

jobs:
  stop-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Stop application and Codespace
        run: |
          echo "Stopping the Codespace 'effective spork'..."
          gh codespace exec --codespace effective-spork -- npm stop
          gh codespace stop --name effective-spork
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
